[package]
name = "example-linear-regression"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
shrew.workspace = true
shrew-core.workspace = true
shrew-cpu.workspace = true
