[package]
name = "example-rnn-sequence"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shrew.workspace = true
shrew-core.workspace = true
shrew-cpu.workspace = true
shrew-nn.workspace = true
shrew-optim.workspace = true
