name: shrew-cli

on:
  push:
    paths:
      - 'crates/shrew-cli/**'
      - '.github/workflows/shrew-cli.yml'
  pull_request:
    paths:
      - 'crates/shrew-cli/**'
      - '.github/workflows/shrew-cli.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --package shrew-cli --verbose
    - name: Run tests
      run: cargo test --package shrew-cli --verbose
